import "@/styles/globals.css";
import { Fira_Sans_Condensed } from "next/font/google";

const fira = Fira_Sans_Condensed({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Orugo | Catálogo de Productos",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="es"
      className="scroll-smooth"
    >
      <body className={`${fira.className} text-zinc-900`}>{children}</body>
    </html>
  );
}
